/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#0f1419',
        surface: '#0f1419',
        'surface-dim': '#0f1419',
        'surface-container-lowest': '#0a0f14',
        'surface-container-low': '#171c21',
        'surface-container': '#1b2025',
        'surface-container-high': '#252a30',
        'surface-container-highest': '#30353b',
        'surface-bright': '#353a3f',
        primary: '#46f1c5',
        'primary-container': '#00d4aa',
        'primary-fixed': '#55fcd0',
        'primary-fixed-dim': '#28dfb5',
        'on-primary': '#00382b',
        'on-primary-fixed': '#002118',
        'on-primary-container': '#005643',
        secondary: '#ffdb9d',
        'secondary-container': '#feb700',
        'secondary-fixed-dim': '#ffba20',
        'on-secondary': '#412d00',
        'on-secondary-container': '#6b4b00',
        tertiary: '#cfd8ec',
        'tertiary-container': '#b3bcd0',
        'on-tertiary': '#283140',
        'on-surface': '#dee3ea',
        'on-surface-variant': '#bacac2',
        outline: '#85948d',
        'outline-variant': '#3b4a44',
        error: '#ffb4ab',
        'error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        sora: ['Sora', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
